export const statesData = [
  { number: 1, name: 'Alabama', description: 'Alabama is the 1st state.' },
  { number: 2, name: 'Alaska', description: 'Alaska is the 2nd state.' },
  { number: 3, name: 'Arizona', description: 'Arizona is the 3rd state.' },
  { number: 4, name: 'Arkansas', description: 'Arkansas is the 4th state.' },
  { number: 5, name: 'California', description: 'California is the 5th state.' },
  { number: 6, name: 'Colorado', description: 'Colorado is the 6th state.' },
  { number: 7, name: 'Connecticut', description: 'Connecticut is the 7th state.' },
  { number: 8, name: 'Delaware', description: 'Delaware is the 8th state.' },
  { number: 9, name: 'Florida', description: 'Florida is the 9th state.' },
  { number: 10, name: 'Georgia', description: 'Georgia is the 10th state.' },
  { number: 11, name: 'Hawaii', description: 'Hawaii is the 11th state.' },
  { number: 12, name: 'Idaho', description: 'Idaho is the 12th state.' },
  { number: 13, name: 'Illinois', description: 'Illinois is the 13th state.' },
  { number: 14, name: 'Indiana', description: 'Indiana is the 14th state.' },
  { number: 15, name: 'Iowa', description: 'Iowa is the 15th state.' },
  { number: 16, name: 'Kansas', description: 'Kansas is the 16th state.' },
  { number: 17, name: 'Kentucky', description: 'Kentucky is the 17th state.' },
  { number: 18, name: 'Louisiana', description: 'Louisiana is the 18th state.' },
  { number: 19, name: 'Maine', description: 'Maine is the 19th state.' },
  { number: 20, name: 'Maryland', description: 'Maryland is the 20th state.' },
  { number: 21, name: 'Massachusetts', description: 'Massachusetts is the 21st state.' },
  { number: 22, name: 'Michigan', description: 'Michigan is the 22nd state.' },
  { number: 23, name: 'Minnesota', description: 'Minnesota is the 23rd state.' },
  { number: 24, name: 'Mississippi', description: 'Mississippi is the 24th state.' },
  { number: 25, name: 'Missouri', description: 'Missouri is the 25th state.' },
  { number: 26, name: 'Montana', description: 'Montana is the 26th state.' },
  { number: 27, name: 'Nebraska', description: 'Nebraska is the 27th state.' },
  { number: 28, name: 'Nevada', description: 'Nevada is the 28th state.' },
  { number: 29, name: 'New Hampshire', description: 'New Hampshire is the 29th state.' },
  { number: 30, name: 'New Jersey', description: 'New Jersey is the 30th state.' },
  { number: 31, name: 'New Mexico', description: 'New Mexico is the 31st state.' },
  { number: 32, name: 'New York', description: 'New York is the 32nd state.' },
  { number: 33, name: 'North Carolina', description: 'North Carolina is the 33rd state.' },
  { number: 34, name: 'North Dakota', description: 'North Dakota is the 34th state.' },
  { number: 35, name: 'Ohio', description: 'Ohio is the 35th state.' },
  { number: 36, name: 'Oklahoma', description: 'Oklahoma is the 36th state.' },
  { number: 37, name: 'Oregon', description: 'Oregon is the 37th state.' },
  { number: 38, name: 'Pennsylvania', description: 'Pennsylvania is the 38th state.' },
  { number: 39, name: 'Rhode Island', description: 'Rhode Island is the 39th state.' },
  { number: 40, name: 'South Carolina', description: 'South Carolina is the 40th state.' },
  { number: 41, name: 'South Dakota', description: 'South Dakota is the 41st state.' },
  { number: 42, name: 'Tennessee', description: 'Tennessee is the 42nd state.' },
  { number: 43, name: 'Texas', description: 'Texas is the 43rd state.' },
  { number: 44, name: 'Utah', description: 'Utah is the 44th state.' },
  { number: 45, name: 'Vermont', description: 'Vermont is the 45th state.' },
  { number: 46, name: 'Virginia', description: 'Virginia is the 46th state.' },
  { number: 47, name: 'Washington', description: 'Washington is the 47th state.' },
  { number: 48, name: 'West Virginia', description: 'West Virginia is the 48th state.' },
  { number: 49, name: 'Wisconsin', description: 'Wisconsin is the 49th state.' },
  { number: 50, name: 'Wyoming', description: 'Wyoming is the 50th state.' },
];

export default statesData;
